Microverse School > Rails > #6 Associations
RaminMammadzada/rails-private-events pull request #6
Opened 2020-10-01 21:49 UTC by RaminMammadzada

- User model, view, controller setup and basic sign in
- Event model, view, controller setup
- Attendance model, view, controller setup
- The associations between Event and User model over the middle table

2020-10-02 01:48 UTC, voscarmv requested changes
# Nice work so far, team. 👍 
## However, there are some changes required 👀 🧰 🔨 🔧 

- When I try to create a new event, I get the following error:

![image](https://user-images.githubusercontent.com/2739245/94879672-7c8fcf80-0426-11eb-90bb-024ebeefb661.png)

I get this error **even though** I did add a Location in the previous step. Please fix this problem so a user can add a new event.

- The date selector for your events is unnecessarily complicated, using 3 different inputs. Please use something like `form.datetime_local_field` instead. You may use [this example](https://github.com/Psiale/private-events/blob/master/app/views/events/_form.html.erb) as a guideline.

Without these initial changes, the project can not be properly tested.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-10-02 19:05 UTC, tirthajyoti-ghosh commented on app/controllers/events_controller.rb
> +      # @events = current_user.events
Please remove this commented code.

2020-10-02 19:08 UTC, tirthajyoti-ghosh commented on app/views/events/_form.html.erb
> +  <% if event.errors.any? %>
There should be absolutely no logic in views. Use helper methods to outsource your view logic.

![image](https://user-images.githubusercontent.com/57726348/94960516-a7eee900-0510-11eb-96e8-60d5f075950d.png)

Use these resources to find out more:
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

2020-10-02 19:09 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +        <% end %>
Please remove this logic from this view.

2020-10-02 19:10 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +        <% end %>
Kindly remove this logic as well.

2020-10-02 19:10 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +        <% end %>
Kindly remove this logic as well.

2020-10-02 19:10 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +        <% end %>
Kindly remove this logic as well.

2020-10-02 19:10 UTC, tirthajyoti-ghosh commented on app/views/events/show.html.erb
> +<%end%>
Kindly remove this logic as well.

2020-10-02 19:11 UTC, tirthajyoti-ghosh commented on app/views/events/show.html.erb
> +      <% end %>
Kindly remove this logic as well.

2020-10-02 19:14 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +    <% @events.upcoming.each do |event| %>
Instead of accessing the upcoming events like this, implement an instance variable that stores the upcoming events. Then access that instance variable from here.

Here is an example: 
`@upcoming_events = Event.upcoming_events`

2020-10-02 19:15 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +    <% @events.past.each do |event| %>
Instead of accessing the past events like this, implement an instance variable that stores the past events. Then access that instance variable from here.

Here is an example: 
```
@past_events = Event.past_events # => this is coming from the scopes in your model
```

2020-10-02 19:17 UTC, tirthajyoti-ghosh commented on app/models/event.rb
> +  # class_name: 'User', foreign_key: 'user_id'
Please remove this comment.

2020-10-02 19:22 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

- When a "not logged in" user tries to create an event, this 👇 error is displayed. Please put a check to prevent guest users from accessing that page.

  ![image](https://user-images.githubusercontent.com/57726348/94960022-c9030a00-050f-11eb-85e6-6034087a5b9e.png)

- In your `events` table, the foreign key that points to the `users` table should be named `creator_id`. Right now, it has a different name. Below is the screenshot from Pathright.
 
  ![image](https://user-images.githubusercontent.com/57726348/94960227-25fec000-0510-11eb-91a3-53f128eb53a0.png)

  Remember to refactor your associations after changing the column name.

_I have left some comments below. Be sure to check them out._

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-10-02 19:22 UTC, tirthajyoti-ghosh commented on app/models/event.rb
> +  # class_name: 'User', foreign_key: 'user_id'
Please remove this comment.

2020-10-02 19:22 UTC, tirthajyoti-ghosh commented on app/controllers/events_controller.rb
> +      # @events = current_user.events
Please remove this commented code.

2020-10-02 19:22 UTC, tirthajyoti-ghosh commented on app/views/events/_form.html.erb
> +  <% if event.errors.any? %>
There should be absolutely no logic in views. Use helper methods to outsource your view logic.

![image](https://user-images.githubusercontent.com/57726348/94960516-a7eee900-0510-11eb-96e8-60d5f075950d.png)

Use these resources to find out more:
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

2020-10-02 19:22 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +    <% @events.past.each do |event| %>
Instead of accessing the past events like this, implement an instance variable that stores the past events. Then access that instance variable from here.

Here is an example: 
```
@past_events = Event.past_events # => this is coming from the scopes in your model
```

2020-10-02 19:22 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +        <% end %>
Please remove this logic from this view.

2020-10-02 19:22 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +        <% end %>
Kindly remove this logic as well.

2020-10-02 19:22 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +    <% @events.upcoming.each do |event| %>
Instead of accessing the upcoming events like this, implement an instance variable that stores the upcoming events. Then access that instance variable from here.

Here is an example: 
`@upcoming_events = Event.upcoming_events`

2020-10-02 19:22 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +        <% end %>
Kindly remove this logic as well.

2020-10-02 19:22 UTC, tirthajyoti-ghosh commented on app/views/events/index.html.erb
> +        <% end %>
Kindly remove this logic as well.

2020-10-02 19:22 UTC, tirthajyoti-ghosh commented on app/views/events/show.html.erb
> +      <% end %>
Kindly remove this logic as well.

2020-10-02 22:00 UTC, RaminMammadzada commented on app/models/event.rb
> +  # class_name: 'User', foreign_key: 'user_id'
Done.

2020-10-02 22:00 UTC, RaminMammadzada commented on app/controllers/events_controller.rb
> +      # @events = current_user.events
Done.

2020-10-02 22:00 UTC, RaminMammadzada commented on app/views/events/_form.html.erb
> +  <% if event.errors.any? %>
Done.

2020-10-02 22:00 UTC, RaminMammadzada commented on app/views/events/index.html.erb
> +    <% @events.past.each do |event| %>
Done.

2020-10-02 22:00 UTC, RaminMammadzada commented on app/views/events/index.html.erb
> +        <% end %>
Done.

2020-10-02 22:00 UTC, RaminMammadzada commented on app/views/events/index.html.erb
> +        <% end %>
Done.

2020-10-02 22:00 UTC, RaminMammadzada commented on app/views/events/index.html.erb
> +    <% @events.upcoming.each do |event| %>
Done.

2020-10-02 22:00 UTC, RaminMammadzada commented on app/views/events/index.html.erb
> +        <% end %>
Done.

2020-10-02 22:00 UTC, RaminMammadzada commented on app/views/events/show.html.erb
> +      <% end %>
Done.

2020-10-03 01:44 UTC, elmejdki requested changes
# status: require changes.
## Great job so far guys :clap: :clap: :clap:, you are almost there you just need to make some minor changes :hammer: :wrench: then your project will be approved :checkered_flag: 

please take a look at the comments below and make sure that they are fixed :wink: 

### Please make all the required changes before you ask for another code review.
## Happy Coding :tophat:

2020-10-03 01:44 UTC, elmejdki commented on app/models/event.rb
> +  # Ex:- scope :active, -> {where(:active => true)}
Pleas remove this commented code

2020-10-03 01:44 UTC, elmejdki commented on app/models/user.rb
> +  # has_many :attended_events, through: :enrollments, source: :event
remove this commented code, you should remove all commented code not just these ones

2020-10-03 01:44 UTC, elmejdki commented on app/views/events/index.html.erb
> +    <% @past_events = Event.past.all %>
put this code inside the model not here, why you have a model then.

2020-10-03 01:44 UTC, elmejdki commented on app/views/events/index.html.erb
> +    <% @upcoming_events = Event.upcoming.all %>
put this code inside the model not here, why you have a model then.

2020-10-03 12:05 UTC, RaminMammadzada commented on app/views/events/index.html.erb
> +    <% @past_events = Event.past.all %>
The previous reviewer said to do that. 
https://github.com/RaminMammadzada/rails-private-events/pull/6#discussion_r499007119

2020-10-03 12:06 UTC, RaminMammadzada commented on app/views/events/index.html.erb
> +    <% @upcoming_events = Event.upcoming.all %>
The previous reviewer sait to do that:
https://github.com/RaminMammadzada/rails-private-events/pull/6#discussion_r499007119

2020-10-03 12:11 UTC, RaminMammadzada commented on app/models/event.rb
> +  # Ex:- scope :active, -> {where(:active => true)}
Done.

2020-10-03 12:11 UTC, RaminMammadzada commented on app/models/user.rb
> +  # has_many :attended_events, through: :enrollments, source: :event
Done.

2020-10-03 12:19 UTC, RaminMammadzada commented on app/views/events/index.html.erb
> +    <% @upcoming_events = Event.upcoming.all %>
I updated it.

2020-10-03 12:19 UTC, RaminMammadzada commented on app/views/events/index.html.erb
> +    <% @past_events = Event.past.all %>
I updated it.

2020-10-03 13:55 UTC, wathigo requested changes
### Changes Required :heavy_multiplication_x: 
Gret job so far :clap: 
However, some suggested changes are yet to be implemented.

See the comments :point_down: 

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

2020-10-03 13:55 UTC, wathigo commented on app/views/events/index.html.erb
> +    <% @events.past.each do |event| %>
Not done!

Lets put:
```ruby 
@past_events = Event.past_events
``` 
in our event controller index action then access it directly from the views as
```ruby
<% @past_events.each do |event| %>
```
Everything connected with data processing should be encapsulated in models and used in controllers.
**Resources:**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

2020-10-03 13:55 UTC, wathigo commented on app/views/events/index.html.erb
> +    <% @events.upcoming.each do |event| %>
Not done!

Lets put:
```ruby 
@upcoming_events = Event.upcoming_events
``` 
in our event controller index action then access it directly from the views as
```ruby
<% @upcoming_events.each do |event| %>
```
Everything connected with data processing should be encapsulated in models and used in controllers.
**Resources:**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

2020-10-03 15:56 UTC, jurgen1c commented on app/views/events/index.html.erb
> +    <% @events.upcoming.each do |event| %>
this is done in the exact same way our names whats different but code executes identically

2020-10-03 16:50 UTC, tirthajyoti-ghosh approved these changes
# Approved ✅

## You have done an incredible job making this project 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of the project. Go ahead and merge it! Onto the next project 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-10-03 18:57 UTC, merged